name: Continuous Integration

on:
    pull_request:
    push:
        branches: [main]
        paths:
            - '**.js'
            - '**.json'
            - '**.ts'
            - '**.tsx'

jobs:
    prettier:
        name: Prettier Check
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Prettify code
              uses: creyD/prettier_action@v4.2
              with:
                  prettier_options: --check .
                  only_changed: true
    build:
        name: Build App
        runs-on: ubuntu-latest
        container: node:lts
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Install PNPM
              run: npm install -g pnpm

            - name: Install Dependencies For PR
              if: github.event_name == 'pull_request'
              run: |
                  pnpm install

            - name: Install Dependencies
              if: github.event_name != 'pull_request'
              run: |
                  pnpm install --frozen-lockfile

            - name: Build App
              run: |
                  pnpm run build
